"""Local encrypted-disk storage backend — envelope encryption, AES-256-GCM.

Per architecture §6.4:
  * each object gets a fresh random 256-bit data key,
  * the data key is wrapped with the master key (from environment / secret store),
  * AES-256-GCM protects both the data key and the object payload, so the GCM tag
    verifies integrity on read (tamper detection).

On-disk format (per object, one file per key):

    magic "VRT1" | version u8 | alg u8 | wrap_nonce(12) | wrapped_data_key(32)
    | file_nonce(12) | ciphertext + GCM tag

The master key is read from ``VERITAS_MASTER_KEY`` (base64 of 32 bytes, or 64 hex
chars). It is NEVER stored on disk next to the data and never hard-coded. ``delete``
overwrites the file with random bytes before unlinking (retention policy §10.4).

Storage keys are opaque identifiers generated by the upload path (UUIDs). The backend
rejects keys that could escape the storage root (path traversal).
"""
from __future__ import annotations

import os
import re
from pathlib import Path

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from .base import StorageBackend, StorageIntegrityError, StorageObject

MAGIC = b"VRT1"
FORMAT_VERSION = 1
ALG_AES256_GCM = 1

WRAP_NONCE_LEN = 12  # nonce protecting the wrapped data key
FILE_NONCE_LEN = 12  # nonce protecting the object payload
DATA_KEY_LEN = 32
TAG_LEN = 16
HEADER_LEN = len(MAGIC) + 1 + 1 + WRAP_NONCE_LEN + (DATA_KEY_LEN + TAG_LEN) + FILE_NONCE_LEN

# Storage keys are opaque tokens (UUIDs in the upload path). Reject anything that
# could traverse directories or hide a file.
_SAFE_KEY_RE = re.compile(r"^[0-9a-zA-Z._-]{1,255}$")


def parse_master_key(raw: str) -> bytes:
    """Accept base64 (32 bytes) or 64-char hex; anything else is a hard error."""
    value = (raw or "").strip()
    if not value:
        raise ValueError(
            "VERITAS_MASTER_KEY is not set. Generate one with "
            "`python -c \"import secrets,base64;print(base64.b64encode(secrets.token_bytes(32)).decode())\"` "
            "and export it (see .env.example)."
        )
    key: bytes | None = None
    # Hex first: a 64-char hex string is also valid base64 (hex chars are in the
    # base64 alphabet), so decoding it as base64 would yield the wrong length.
    if len(value) == 64:
        try:
            key = bytes.fromhex(value)
        except ValueError:
            key = None
    if key is None:
        import base64

        try:
            key = base64.b64decode(value, validate=True)
        except Exception:
            key = None
    if key is None or len(key) != DATA_KEY_LEN:
        raise ValueError(
            "VERITAS_MASTER_KEY must be 32 bytes (base64-encoded) or 64 hex characters."
        )
    return key


class LocalEncryptedStorage(StorageBackend):
    """Encrypted local-disk implementation of StorageBackend (MVP backend)."""

    def __init__(self, root: str | Path, master_key: str | bytes) -> None:
        self.root = Path(root).resolve()
        self.master_key = parse_master_key(master_key) if isinstance(master_key, str) else master_key
        if len(self.master_key) != DATA_KEY_LEN:  # pragma: no cover - parse_master_key guards
            raise ValueError("master key must be 32 bytes")
        self.root.mkdir(parents=True, exist_ok=True)

    # -- key handling ---------------------------------------------------------

    def _path_for(self, key: str) -> Path:
        if not _SAFE_KEY_RE.match(key) or ".." in key:
            raise ValueError(f"unsafe storage key: {key!r}")
        return self.root / key

    # -- StorageBackend -------------------------------------------------------

    def put(self, key: str, data: bytes, *, content_type: str = "application/octet-stream") -> StorageObject:
        path = self._path_for(key)
        blob = self._encrypt(data)
        # Atomic write: write to a temp file in the same dir, then rename.
        tmp = path.with_suffix(path.suffix + ".tmp")
        tmp.write_bytes(blob)
        os.replace(tmp, path)
        return StorageObject(key=key, content_type=content_type, size_bytes=len(data))

    def get(self, key: str) -> bytes:
        path = self._path_for(key)
        if not path.exists():
            raise KeyError(f"no such object: {key!r}")
        return self._decrypt(path.read_bytes())

    def exists(self, key: str) -> bool:
        return self._path_for(key).exists()

    def delete(self, key: str) -> None:
        path = self._path_for(key)
        if not path.exists():
            return
        # Retention §10.4: overwrite with random bytes before unlink, so a
        # recovered disk block does not yield ciphertext of a deleted object.
        size = path.stat().st_size
        with path.open("r+b") as fh:
            fh.write(os.urandom(size))
            fh.flush()
            os.fsync(fh.fileno())
        path.unlink()

    # -- crypto ---------------------------------------------------------------

    def _encrypt(self, data: bytes) -> bytes:
        data_key = os.urandom(DATA_KEY_LEN)
        wrap_nonce = os.urandom(WRAP_NONCE_LEN)
        file_nonce = os.urandom(FILE_NONCE_LEN)

        wrapped_key = AESGCM(self.master_key).encrypt(wrap_nonce, data_key, None)
        ciphertext = AESGCM(data_key).encrypt(file_nonce, data, None)

        return (
            MAGIC
            + bytes([FORMAT_VERSION, ALG_AES256_GCM])
            + wrap_nonce
            + wrapped_key
            + file_nonce
            + ciphertext
        )

    def _decrypt(self, blob: bytes) -> bytes:
        if len(blob) < HEADER_LEN or blob[:4] != MAGIC:
            raise StorageIntegrityError("object header is invalid or corrupt")
        version, alg = blob[4], blob[5]
        if version != FORMAT_VERSION or alg != ALG_AES256_GCM:
            raise StorageIntegrityError(f"unsupported object format version={version} alg={alg}")

        wrap_nonce = blob[6 : 6 + WRAP_NONCE_LEN]
        wrapped_key = blob[6 + WRAP_NONCE_LEN : 6 + WRAP_NONCE_LEN + DATA_KEY_LEN + TAG_LEN]
        file_nonce_start = 6 + WRAP_NONCE_LEN + DATA_KEY_LEN + TAG_LEN
        file_nonce = blob[file_nonce_start : file_nonce_start + FILE_NONCE_LEN]
        ciphertext = blob[file_nonce_start + FILE_NONCE_LEN :]

        try:
            data_key = AESGCM(self.master_key).decrypt(wrap_nonce, wrapped_key, None)
        except InvalidTag as exc:
            raise StorageIntegrityError("data key unwrap failed (master key mismatch?)") from exc
        try:
            return AESGCM(data_key).decrypt(file_nonce, ciphertext, None)
        except InvalidTag as exc:
            raise StorageIntegrityError("payload integrity check failed (tampered or corrupt)") from exc
